default_context:
  project_name: 'DashAPI'
  project_slug: 'dashapi'
  domain_main: 'localhost'
  domain_staging: 'stag.localhost'
  docker_swarm_stack_name_main: 'localhost'
  docker_swarm_stack_name_staging: 'stag-localhost'
  secret_key: 'pwd'
  first_superuser: 'christophereek97@gmail.com'
  first_superuser_password: 'pwd'
  backend_cors_origins: '["http://localhost:8080","http://172.19.36.52:8080","http://localhost","http://localhost:4200","http://localhost:3000","http://dev.mifarmacia.app","https://stag.mifarmacia.app","https://mifarmacia.app","http://local.dockertoolbox.tiangolo.com","http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'christophereek97@gmail.com'
  postgres_password: 'pwd'
  pgadmin_default_user: 'christophereek97@gmail.com'
  pgadmin_default_user_password: 'pwd'
  traefik_constraint_tag: 'localhost'
  traefik_constraint_tag_staging: 'stag.localhost'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:pwd'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
